# Edition of the sources file 
# Please choose between molecule, desktop, custom and server
# NOTE: With a custom edition it doesn't download any configuration files so it has to be created manually.
edition: molecule

# The version of the sources file
version: 0.0.1-dev

# Downloading the latest upstream-source.yml file from official source.
# NOTE: This option will be ignored if the file .lock-sources exist in the root folder.
#       Updating the sources file will be disabled.
update-sources: true